# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 16:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedRuns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pins', models.CharField(max_length=1000)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime(2016, 5, 14, 19, 3, 39, 188444))),
            ],
        ),
    ]
